local_backend: true
backend:
    name: git-gateway
    branch: main

site_url: http://127.0.0.1:5500
display_url: http://127.0.0.1:5500

media_folder: media

collections:
    - name: pages
      label: Pages
      editor:
          preview: false
      files:
          - name: index
            label: Home
            file: data.json
            fields:
                - { name: title, label: Title, widget: string }
                - { name: description, label: Description, widget: string }
